#%Module1.0

#- Hello world, who am I?
set product redrock
set version {version}
conflict $product

#- Some modules stuff
proc ModulesHelp {{ }} {{
    global product version
    puts stderr "This module adds $product/$version to your environment."
}}
module-whatis "Sets up $product/$version in your environment."

#- Dependencies
# module load desiUtil
# prereq desiUtil

#- Default code location
if {{[info exists env(DESI_PRODUCT_ROOT)]}} {{
    set PRODUCT_ROOT $env(DESI_PRODUCT_ROOT)
}} else {{
    set PRODUCT_ROOT /project/projectdirs/desi/software/$env(NERSC_HOST)
}}
set PRODUCT_DIR $PRODUCT_ROOT/$product/$version

#- Set $REDROCK environment variable
setenv [string toupper $product] $PRODUCT_DIR

#- Update $PATH and $PYTHONPATH
prepend-path PATH $PRODUCT_DIR/bin
### prepend-path PYTHONPATH $PRODUCT_DIR/lib/{pyversion}/site-packages
prepend-path PYTHONPATH $PRODUCT_DIR/py
