#%Module1.0

#- Hello world, who am I?
set product redrock
set version {version}
conflict $product

#- Some modules stuff
proc ModulesHelp {{ }} {{
    global product version
    puts stderr "This module adds $product/$version to your environment."
}}
module-whatis "Sets up $product/$version in your environment."

#- Default code location
if {{[info exists env(DESI_PRODUCT_ROOT)]}} {{
    set code_root $env(DESI_PRODUCT_ROOT)/code
}} else {{
    set code_root {product_root}
}}
set PRODUCT_DIR $code_root/$product/$version

#- Set $REDROCK environment variable
setenv [string toupper $product] $PRODUCT_DIR

#- Update $PATH and $PYTHONPATH
prepend-path PATH $PRODUCT_DIR/bin
### prepend-path PYTHONPATH $PRODUCT_DIR/lib/{pyversion}/site-packages
prepend-path PYTHONPATH $PRODUCT_DIR/py

#- MPI or multiprocessing handle parallelism, not OpenMP via numpy/MKL
setenv KMP_AFFINITY disabled
setenv MPICH_GNI_FORK_MODE FULLCOPY
setenv OMP_NUM_THREADS 1
